package com.sfxie.services.center.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table report_definition
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class ReportDefinition {
    /**
     *  主键,所属表字段为report_definition.id
     */
    private Long id;

    /**
     *  报表编码,所属表字段为report_definition.code
     */
    private String code;

    /**
     *  名称,所属表字段为report_definition.name
     */
    private String name;

    /**
     *  创建时间 ,所属表字段为report_definition.create_time
     */
    private Date createTime;

    /**
     *  是否主报表 : Y-是,N-否,所属表字段为report_definition.is_main
     */
    private String isMain;

    /**
     * 获取 主键 字段:report_definition.id
     *
     * @return report_definition.id, 主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置 主键 字段:report_definition.id
     *
     * @param id report_definition.id, 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 报表编码 字段:report_definition.code
     *
     * @return report_definition.code, 报表编码
     */
    public String getCode() {
        return code;
    }

    /**
     * 设置 报表编码 字段:report_definition.code
     *
     * @param code report_definition.code, 报表编码
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * 获取 名称 字段:report_definition.name
     *
     * @return report_definition.name, 名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 名称 字段:report_definition.name
     *
     * @param name report_definition.name, 名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 创建时间  字段:report_definition.create_time
     *
     * @return report_definition.create_time, 创建时间 
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间  字段:report_definition.create_time
     *
     * @param createTime report_definition.create_time, 创建时间 
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 是否主报表 : Y-是,N-否 字段:report_definition.isMain
     *
     * @return report_definition.isMain, 是否主报表 : Y-是,N-否
     */
    public String getIsMain() {
        return isMain;
    }

    /**
     * 设置 是否主报表 : Y-是,N-否 字段:report_definition.isMain
     *
     * @param ismain report_definition.isMain, 是否主报表 : Y-是,N-否
     */
    public void setIsmain(String ismain) {
        this.isMain = ismain == null ? null : ismain.trim();
    }
}