package com.sfxie.services.center.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table report_version
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class ReportVersionWithBLOBs extends ReportVersion {
    /**
     *  报表源代码,所属表字段为report_version.source_jrxml
     */
    private String sourceJrxml;

    /**
     *  java数据源,所属表字段为report_version.dataset_java
     */
    private String datasetJava;

    /**
     *  报表编译后代码,所属表字段为report_version.source_jasper
     */
    private String sourceJasper;

    /**
     * 获取 报表源代码 字段:report_version.source_jrxml
     *
     * @return report_version.source_jrxml, 报表源代码
     */
    public String getSourceJrxml() {
        return sourceJrxml;
    }

    /**
     * 设置 报表源代码 字段:report_version.source_jrxml
     *
     * @param sourceJrxml report_version.source_jrxml, 报表源代码
     */
    public void setSourceJrxml(String sourceJrxml) {
        this.sourceJrxml = sourceJrxml == null ? null : sourceJrxml.trim();
    }

    /**
     * 获取 java数据源 字段:report_version.dataset_java
     *
     * @return report_version.dataset_java, java数据源
     */
    public String getDatasetJava() {
        return datasetJava;
    }

    /**
     * 设置 java数据源 字段:report_version.dataset_java
     *
     * @param datasetJava report_version.dataset_java, java数据源
     */
    public void setDatasetJava(String datasetJava) {
        this.datasetJava = datasetJava == null ? null : datasetJava.trim();
    }

    /**
     * 获取 报表编译后代码 字段:report_version.source_jasper
     *
     * @return report_version.source_jasper, 报表编译后代码
     */
    public String getSourceJasper() {
        return sourceJasper;
    }

    /**
     * 设置 报表编译后代码 字段:report_version.source_jasper
     *
     * @param sourceJasper report_version.source_jasper, 报表编译后代码
     */
    public void setSourceJasper(String sourceJasper) {
        this.sourceJasper = sourceJasper == null ? null : sourceJasper.trim();
    }
}