package com.sfxie.services.center.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table report_parameter
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class ReportParameter {
    /**
     *  主键,所属表字段为report_parameter.id
     */
    private Long id;

    /**
     *  创建时间 ,所属表字段为report_parameter.create_time
     */
    private Date createTime;

    /**
     *  名称,所属表字段为report_parameter.name
     */
    private String name;

    /**
     *  参数类型,所属表字段为report_parameter.type
     */
    private String type;

    /**
     *  默认值,所属表字段为report_parameter.value
     */
    private String value;

    /**
     *  参数校验器,所属表字段为report_parameter.validator
     */
    private String validator;

    /**
     *  报表参数显示类型,所属表字段为report_parameter.element_type
     */
    private String elementType;

    /**
     *  前端显示,所属表字段为report_parameter.title
     */
    private String title;

    /**
     *  参数数据提供者,所属表字段为report_parameter.data_provider
     */
    private String dataProvider;

    /**
     * 获取 主键 字段:report_parameter.id
     *
     * @return report_parameter.id, 主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置 主键 字段:report_parameter.id
     *
     * @param id report_parameter.id, 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 创建时间  字段:report_parameter.create_time
     *
     * @return report_parameter.create_time, 创建时间 
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间  字段:report_parameter.create_time
     *
     * @param createTime report_parameter.create_time, 创建时间 
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 名称 字段:report_parameter.name
     *
     * @return report_parameter.name, 名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 名称 字段:report_parameter.name
     *
     * @param name report_parameter.name, 名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 参数类型 字段:report_parameter.type
     *
     * @return report_parameter.type, 参数类型
     */
    public String getType() {
        return type;
    }

    /**
     * 设置 参数类型 字段:report_parameter.type
     *
     * @param type report_parameter.type, 参数类型
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * 获取 默认值 字段:report_parameter.value
     *
     * @return report_parameter.value, 默认值
     */
    public String getValue() {
        return value;
    }

    /**
     * 设置 默认值 字段:report_parameter.value
     *
     * @param value report_parameter.value, 默认值
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * 获取 参数校验器 字段:report_parameter.validator
     *
     * @return report_parameter.validator, 参数校验器
     */
    public String getValidator() {
        return validator;
    }

    /**
     * 设置 参数校验器 字段:report_parameter.validator
     *
     * @param validator report_parameter.validator, 参数校验器
     */
    public void setValidator(String validator) {
        this.validator = validator == null ? null : validator.trim();
    }

    /**
     * 获取 报表参数显示类型 字段:report_parameter.element_type
     *
     * @return report_parameter.element_type, 报表参数显示类型
     */
    public String getElementType() {
        return elementType;
    }

    /**
     * 设置 报表参数显示类型 字段:report_parameter.element_type
     *
     * @param elementType report_parameter.element_type, 报表参数显示类型
     */
    public void setElementType(String elementType) {
        this.elementType = elementType == null ? null : elementType.trim();
    }

    /**
     * 获取 前端显示 字段:report_parameter.title
     *
     * @return report_parameter.title, 前端显示
     */
    public String getTitle() {
        return title;
    }

    /**
     * 设置 前端显示 字段:report_parameter.title
     *
     * @param title report_parameter.title, 前端显示
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 获取 参数数据提供者 字段:report_parameter.data_provider
     *
     * @return report_parameter.data_provider, 参数数据提供者
     */
    public String getDataProvider() {
        return dataProvider;
    }

    /**
     * 设置 参数数据提供者 字段:report_parameter.data_provider
     *
     * @param dataProvider report_parameter.data_provider, 参数数据提供者
     */
    public void setDataProvider(String dataProvider) {
        this.dataProvider = dataProvider == null ? null : dataProvider.trim();
    }
}