package com.sfxie.services.center.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table report_active
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class ReportActive {
    /**
     *  主键,所属表字段为report_active.id
     */
    private Long id;

    /**
     *  报表定义id,所属表字段为report_active.report_id
     */
    private Long reportId;

    /**
     *  报表版本id,所属表字段为report_active.version_id
     */
    private Long versionId;

    /**
     *  创建时间 ,所属表字段为report_active.create_time
     */
    private Date createTime;

    /**
     * 获取 主键 字段:report_active.id
     *
     * @return report_active.id, 主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置 主键 字段:report_active.id
     *
     * @param id report_active.id, 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 报表定义id 字段:report_active.report_id
     *
     * @return report_active.report_id, 报表定义id
     */
    public Long getReportId() {
        return reportId;
    }

    /**
     * 设置 报表定义id 字段:report_active.report_id
     *
     * @param reportId report_active.report_id, 报表定义id
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * 获取 报表版本id 字段:report_active.version_id
     *
     * @return report_active.version_id, 报表版本id
     */
    public Long getVersionId() {
        return versionId;
    }

    /**
     * 设置 报表版本id 字段:report_active.version_id
     *
     * @param versionId report_active.version_id, 报表版本id
     */
    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }

    /**
     * 获取 创建时间  字段:report_active.create_time
     *
     * @return report_active.create_time, 创建时间 
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间  字段:report_active.create_time
     *
     * @param createTime report_active.create_time, 创建时间 
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}