package com.sfxie.services.center.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table report_version
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class ReportVersion {
    /**
     *  主键,所属表字段为report_version.id
     */
    private Long id;

    /**
     *  创建时间 ,所属表字段为report_version.create_time
     */
    private Date createTime;

    /**
     *  报表定义id,所属表字段为report_version.report_id
     */
    private Long reportId;

    /**
     *  报表版本号,所属表字段为report_version.version
     */
    private String version;

    /**
     *  报表描述,所属表字段为report_version.description
     */
    private String description;

    /**
     * 获取 主键 字段:report_version.id
     *
     * @return report_version.id, 主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置 主键 字段:report_version.id
     *
     * @param id report_version.id, 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 创建时间  字段:report_version.create_time
     *
     * @return report_version.create_time, 创建时间 
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间  字段:report_version.create_time
     *
     * @param createTime report_version.create_time, 创建时间 
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 报表定义id 字段:report_version.report_id
     *
     * @return report_version.report_id, 报表定义id
     */
    public Long getReportId() {
        return reportId;
    }

    /**
     * 设置 报表定义id 字段:report_version.report_id
     *
     * @param reportId report_version.report_id, 报表定义id
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * 获取 报表版本号 字段:report_version.version
     *
     * @return report_version.version, 报表版本号
     */
    public String getVersion() {
        return version;
    }

    /**
     * 设置 报表版本号 字段:report_version.version
     *
     * @param version report_version.version, 报表版本号
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * 获取 报表描述 字段:report_version.description
     *
     * @return report_version.description, 报表描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置 报表描述 字段:report_version.description
     *
     * @param description report_version.description, 报表描述
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}