package com.sfxie.services.center.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table report_server_register
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class ReportServerRegister {
    /**
     *  主键,所属表字段为report_server_register.id
     */
    private Long id;

    /**
     *  名称,所属表字段为report_server_register.name
     */
    private String name;

    /**
     *  创建时间 ,所属表字段为report_server_register.create_time
     */
    private Date createTime;

    /**
     *  主机,所属表字段为report_server_register.host
     */
    private String host;

    /**
     *  端口,所属表字段为report_server_register.port
     */
    private String port;

    /**
     * 获取 主键 字段:report_server_register.id
     *
     * @return report_server_register.id, 主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置 主键 字段:report_server_register.id
     *
     * @param id report_server_register.id, 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 名称 字段:report_server_register.name
     *
     * @return report_server_register.name, 名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 名称 字段:report_server_register.name
     *
     * @param name report_server_register.name, 名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 创建时间  字段:report_server_register.create_time
     *
     * @return report_server_register.create_time, 创建时间 
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间  字段:report_server_register.create_time
     *
     * @param createTime report_server_register.create_time, 创建时间 
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 主机 字段:report_server_register.host
     *
     * @return report_server_register.host, 主机
     */
    public String getHost() {
        return host;
    }

    /**
     * 设置 主机 字段:report_server_register.host
     *
     * @param host report_server_register.host, 主机
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * 获取 端口 字段:report_server_register.port
     *
     * @return report_server_register.port, 端口
     */
    public String getPort() {
        return port;
    }

    /**
     * 设置 端口 字段:report_server_register.port
     *
     * @param port report_server_register.port, 端口
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }
}