package com.sfxie.services.center.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table report_parameter_definition_version
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class ReportParameterDefinitionVersion {
    /**
     *  主键,所属表字段为report_parameter_definition_version.id
     */
    private Long id;

    /**
     *  报表参数表id,所属表字段为report_parameter_definition_version.parameter_id
     */
    private Long parameterId;

    /**
     *  报表定义id,所属表字段为report_parameter_definition_version.report_id
     */
    private Long reportId;

    /**
     *  报表版本id,所属表字段为report_parameter_definition_version.version_id
     */
    private Long versionId;

    /**
     * 获取 主键 字段:report_parameter_definition_version.id
     *
     * @return report_parameter_definition_version.id, 主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置 主键 字段:report_parameter_definition_version.id
     *
     * @param id report_parameter_definition_version.id, 主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 报表参数表id 字段:report_parameter_definition_version.parameter_id
     *
     * @return report_parameter_definition_version.parameter_id, 报表参数表id
     */
    public Long getParameterId() {
        return parameterId;
    }

    /**
     * 设置 报表参数表id 字段:report_parameter_definition_version.parameter_id
     *
     * @param parameterId report_parameter_definition_version.parameter_id, 报表参数表id
     */
    public void setParameterId(Long parameterId) {
        this.parameterId = parameterId;
    }

    /**
     * 获取 报表定义id 字段:report_parameter_definition_version.report_id
     *
     * @return report_parameter_definition_version.report_id, 报表定义id
     */
    public Long getReportId() {
        return reportId;
    }

    /**
     * 设置 报表定义id 字段:report_parameter_definition_version.report_id
     *
     * @param reportId report_parameter_definition_version.report_id, 报表定义id
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * 获取 报表版本id 字段:report_parameter_definition_version.version_id
     *
     * @return report_parameter_definition_version.version_id, 报表版本id
     */
    public Long getVersionId() {
        return versionId;
    }

    /**
     * 设置 报表版本id 字段:report_parameter_definition_version.version_id
     *
     * @param versionId report_parameter_definition_version.version_id, 报表版本id
     */
    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }
}