package com.sfxie.services.center.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sfxie_sys_role_action
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class SfxieSysRoleAction {
    /**
     *  记录主键 : 记录主键,所属表字段为sfxie_sys_role_action.id_
     */
    private String id;

    /**
     *  操作主键 : 操作主键,所属表字段为sfxie_sys_role_action.action_id
     */
    private String actionId;

    /**
     *  角色菜单关联表id : 关联角色菜单关联表id,所属表字段为sfxie_sys_role_action.role_menu_id
     */
    private String roleMenuId;

    /**
     *  上一级公司 : 上上一级公司，也就是这一级的上一级公司,所属表字段为sfxie_sys_role_action.owner_company_code
     */
    private String ownerCompanyCode;

    /**
     *  是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效,所属表字段为sfxie_sys_role_action.is_valid
     */
    private String isValid;

    /**
     *  公司角色关联表id : 公司角色关联表id,所属表字段为sfxie_sys_role_action.company_role_id
     */
    private String companyRoleId;

    /**
     *  参数标记 : 如果链接中有参数，则设置参数标记。如:businessType=modify,所属表字段为sfxie_sys_role_action.param_flag
     */
    private String paramFlag;

    /**
     *  分区字段 : 分区字段,从用户公司代码字段取值,所属表字段为sfxie_sys_role_action.partition_company
     */
    private String partitionCompany;

    /**
     * 获取 记录主键 : 记录主键 字段:sfxie_sys_role_action.id_
     *
     * @return sfxie_sys_role_action.id_, 记录主键 : 记录主键
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 记录主键 : 记录主键 字段:sfxie_sys_role_action.id_
     *
     * @param id sfxie_sys_role_action.id_, 记录主键 : 记录主键
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 操作主键 : 操作主键 字段:sfxie_sys_role_action.action_id
     *
     * @return sfxie_sys_role_action.action_id, 操作主键 : 操作主键
     */
    public String getActionId() {
        return actionId;
    }

    /**
     * 设置 操作主键 : 操作主键 字段:sfxie_sys_role_action.action_id
     *
     * @param actionId sfxie_sys_role_action.action_id, 操作主键 : 操作主键
     */
    public void setActionId(String actionId) {
        this.actionId = actionId == null ? null : actionId.trim();
    }

    /**
     * 获取 角色菜单关联表id : 关联角色菜单关联表id 字段:sfxie_sys_role_action.role_menu_id
     *
     * @return sfxie_sys_role_action.role_menu_id, 角色菜单关联表id : 关联角色菜单关联表id
     */
    public String getRoleMenuId() {
        return roleMenuId;
    }

    /**
     * 设置 角色菜单关联表id : 关联角色菜单关联表id 字段:sfxie_sys_role_action.role_menu_id
     *
     * @param roleMenuId sfxie_sys_role_action.role_menu_id, 角色菜单关联表id : 关联角色菜单关联表id
     */
    public void setRoleMenuId(String roleMenuId) {
        this.roleMenuId = roleMenuId == null ? null : roleMenuId.trim();
    }

    /**
     * 获取 上一级公司 : 上上一级公司，也就是这一级的上一级公司 字段:sfxie_sys_role_action.owner_company_code
     *
     * @return sfxie_sys_role_action.owner_company_code, 上一级公司 : 上上一级公司，也就是这一级的上一级公司
     */
    public String getOwnerCompanyCode() {
        return ownerCompanyCode;
    }

    /**
     * 设置 上一级公司 : 上上一级公司，也就是这一级的上一级公司 字段:sfxie_sys_role_action.owner_company_code
     *
     * @param ownerCompanyCode sfxie_sys_role_action.owner_company_code, 上一级公司 : 上上一级公司，也就是这一级的上一级公司
     */
    public void setOwnerCompanyCode(String ownerCompanyCode) {
        this.ownerCompanyCode = ownerCompanyCode == null ? null : ownerCompanyCode.trim();
    }

    /**
     * 获取 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_role_action.is_valid
     *
     * @return sfxie_sys_role_action.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * 设置 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_role_action.is_valid
     *
     * @param isValid sfxie_sys_role_action.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * 获取 公司角色关联表id : 公司角色关联表id 字段:sfxie_sys_role_action.company_role_id
     *
     * @return sfxie_sys_role_action.company_role_id, 公司角色关联表id : 公司角色关联表id
     */
    public String getCompanyRoleId() {
        return companyRoleId;
    }

    /**
     * 设置 公司角色关联表id : 公司角色关联表id 字段:sfxie_sys_role_action.company_role_id
     *
     * @param companyRoleId sfxie_sys_role_action.company_role_id, 公司角色关联表id : 公司角色关联表id
     */
    public void setCompanyRoleId(String companyRoleId) {
        this.companyRoleId = companyRoleId == null ? null : companyRoleId.trim();
    }

    /**
     * 获取 参数标记 : 如果链接中有参数，则设置参数标记。如:businessType=modify 字段:sfxie_sys_role_action.param_flag
     *
     * @return sfxie_sys_role_action.param_flag, 参数标记 : 如果链接中有参数，则设置参数标记。如:businessType=modify
     */
    public String getParamFlag() {
        return paramFlag;
    }

    /**
     * 设置 参数标记 : 如果链接中有参数，则设置参数标记。如:businessType=modify 字段:sfxie_sys_role_action.param_flag
     *
     * @param paramFlag sfxie_sys_role_action.param_flag, 参数标记 : 如果链接中有参数，则设置参数标记。如:businessType=modify
     */
    public void setParamFlag(String paramFlag) {
        this.paramFlag = paramFlag == null ? null : paramFlag.trim();
    }

    /**
     * 获取 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_role_action.partition_company
     *
     * @return sfxie_sys_role_action.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public String getPartitionCompany() {
        return partitionCompany;
    }

    /**
     * 设置 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_role_action.partition_company
     *
     * @param partitionCompany sfxie_sys_role_action.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public void setPartitionCompany(String partitionCompany) {
        this.partitionCompany = partitionCompany == null ? null : partitionCompany.trim();
    }
}