package com.sfxie.services.center.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sfxie_sys_authorization
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class SfxieSysAuthorization {
    /**
     *  记录主键 : 记录主键,所属表字段为sfxie_sys_authorization.id_
     */
    private String id;

    /**
     *  角色代码 : 角色代码,所属表字段为sfxie_sys_authorization.role_code
     */
    private String roleCode;

    /**
     *  公司代码 : 关联公司代码,表明创建公司,所属表字段为sfxie_sys_authorization.company_code
     */
    private String companyCode;

    /**
     *  部门代码 : 部门代码,所属表字段为sfxie_sys_authorization.department_code
     */
    private String departmentCode;

    /**
     *  岗位代码 : 岗位代码,所属表字段为sfxie_sys_authorization.post_code
     */
    private String postCode;

    /**
     *  是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效,所属表字段为sfxie_sys_authorization.is_valid
     */
    private String isValid;

    /**
     *  创建时间 : 创建时间,所属表字段为sfxie_sys_authorization.create_time
     */
    private Date createTime;

    /**
     *  创建公司 : 创建公司,所属表字段为sfxie_sys_authorization.create_company_code
     */
    private String createCompanyCode;

    /**
     *  记录创建人 : 记录创建人,所属表字段为sfxie_sys_authorization.create_user
     */
    private String createUser;

    /**
     *  分区字段 : 分区字段,从用户公司代码字段取值,所属表字段为sfxie_sys_authorization.partition_company
     */
    private String partitionCompany;

    /**
     * 获取 记录主键 : 记录主键 字段:sfxie_sys_authorization.id_
     *
     * @return sfxie_sys_authorization.id_, 记录主键 : 记录主键
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 记录主键 : 记录主键 字段:sfxie_sys_authorization.id_
     *
     * @param id sfxie_sys_authorization.id_, 记录主键 : 记录主键
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 角色代码 : 角色代码 字段:sfxie_sys_authorization.role_code
     *
     * @return sfxie_sys_authorization.role_code, 角色代码 : 角色代码
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * 设置 角色代码 : 角色代码 字段:sfxie_sys_authorization.role_code
     *
     * @param roleCode sfxie_sys_authorization.role_code, 角色代码 : 角色代码
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * 获取 公司代码 : 关联公司代码,表明创建公司 字段:sfxie_sys_authorization.company_code
     *
     * @return sfxie_sys_authorization.company_code, 公司代码 : 关联公司代码,表明创建公司
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * 设置 公司代码 : 关联公司代码,表明创建公司 字段:sfxie_sys_authorization.company_code
     *
     * @param companyCode sfxie_sys_authorization.company_code, 公司代码 : 关联公司代码,表明创建公司
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * 获取 部门代码 : 部门代码 字段:sfxie_sys_authorization.department_code
     *
     * @return sfxie_sys_authorization.department_code, 部门代码 : 部门代码
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * 设置 部门代码 : 部门代码 字段:sfxie_sys_authorization.department_code
     *
     * @param departmentCode sfxie_sys_authorization.department_code, 部门代码 : 部门代码
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * 获取 岗位代码 : 岗位代码 字段:sfxie_sys_authorization.post_code
     *
     * @return sfxie_sys_authorization.post_code, 岗位代码 : 岗位代码
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * 设置 岗位代码 : 岗位代码 字段:sfxie_sys_authorization.post_code
     *
     * @param postCode sfxie_sys_authorization.post_code, 岗位代码 : 岗位代码
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * 获取 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_authorization.is_valid
     *
     * @return sfxie_sys_authorization.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * 设置 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_authorization.is_valid
     *
     * @param isValid sfxie_sys_authorization.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * 获取 创建时间 : 创建时间 字段:sfxie_sys_authorization.create_time
     *
     * @return sfxie_sys_authorization.create_time, 创建时间 : 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 : 创建时间 字段:sfxie_sys_authorization.create_time
     *
     * @param createTime sfxie_sys_authorization.create_time, 创建时间 : 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 创建公司 : 创建公司 字段:sfxie_sys_authorization.create_company_code
     *
     * @return sfxie_sys_authorization.create_company_code, 创建公司 : 创建公司
     */
    public String getCreateCompanyCode() {
        return createCompanyCode;
    }

    /**
     * 设置 创建公司 : 创建公司 字段:sfxie_sys_authorization.create_company_code
     *
     * @param createCompanyCode sfxie_sys_authorization.create_company_code, 创建公司 : 创建公司
     */
    public void setCreateCompanyCode(String createCompanyCode) {
        this.createCompanyCode = createCompanyCode == null ? null : createCompanyCode.trim();
    }

    /**
     * 获取 记录创建人 : 记录创建人 字段:sfxie_sys_authorization.create_user
     *
     * @return sfxie_sys_authorization.create_user, 记录创建人 : 记录创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * 设置 记录创建人 : 记录创建人 字段:sfxie_sys_authorization.create_user
     *
     * @param createUser sfxie_sys_authorization.create_user, 记录创建人 : 记录创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * 获取 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_authorization.partition_company
     *
     * @return sfxie_sys_authorization.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public String getPartitionCompany() {
        return partitionCompany;
    }

    /**
     * 设置 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_authorization.partition_company
     *
     * @param partitionCompany sfxie_sys_authorization.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public void setPartitionCompany(String partitionCompany) {
        this.partitionCompany = partitionCompany == null ? null : partitionCompany.trim();
    }
}