package com.sfxie.services.center.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sfxie_sys_auth_role_menu
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class SfxieSysAuthRoleMenu {
    /**
     *  记录主键 : 记录主键,所属表字段为sfxie_sys_auth_role_menu.id_
     */
    private String id;

    /**
     *  是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效,所属表字段为sfxie_sys_auth_role_menu.is_valid
     */
    private String isValid;

    /**
     *  角色菜单关联表id : 关联角色菜单关联表id,所属表字段为sfxie_sys_auth_role_menu.role_menu_id
     */
    private String roleMenuId;

    /**
     *  数据权限表id : 关联数据权限表id,所属表字段为sfxie_sys_auth_role_menu.auth_data_id
     */
    private String authDataId;

    /**
     *  上一级公司 : 上上一级公司，也就是这一级的上一级公司,所属表字段为sfxie_sys_auth_role_menu.owner_company_code
     */
    private String ownerCompanyCode;

    /**
     *  公司角色关联表id : 公司角色关联表id,所属表字段为sfxie_sys_auth_role_menu.company_role_id
     */
    private String companyRoleId;

    /**
     *  分区字段 : 分区字段,从用户公司代码字段取值,所属表字段为sfxie_sys_auth_role_menu.partition_company
     */
    private String partitionCompany;

    /**
     * 获取 记录主键 : 记录主键 字段:sfxie_sys_auth_role_menu.id_
     *
     * @return sfxie_sys_auth_role_menu.id_, 记录主键 : 记录主键
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 记录主键 : 记录主键 字段:sfxie_sys_auth_role_menu.id_
     *
     * @param id sfxie_sys_auth_role_menu.id_, 记录主键 : 记录主键
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_auth_role_menu.is_valid
     *
     * @return sfxie_sys_auth_role_menu.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * 设置 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_auth_role_menu.is_valid
     *
     * @param isValid sfxie_sys_auth_role_menu.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * 获取 角色菜单关联表id : 关联角色菜单关联表id 字段:sfxie_sys_auth_role_menu.role_menu_id
     *
     * @return sfxie_sys_auth_role_menu.role_menu_id, 角色菜单关联表id : 关联角色菜单关联表id
     */
    public String getRoleMenuId() {
        return roleMenuId;
    }

    /**
     * 设置 角色菜单关联表id : 关联角色菜单关联表id 字段:sfxie_sys_auth_role_menu.role_menu_id
     *
     * @param roleMenuId sfxie_sys_auth_role_menu.role_menu_id, 角色菜单关联表id : 关联角色菜单关联表id
     */
    public void setRoleMenuId(String roleMenuId) {
        this.roleMenuId = roleMenuId == null ? null : roleMenuId.trim();
    }

    /**
     * 获取 数据权限表id : 关联数据权限表id 字段:sfxie_sys_auth_role_menu.auth_data_id
     *
     * @return sfxie_sys_auth_role_menu.auth_data_id, 数据权限表id : 关联数据权限表id
     */
    public String getAuthDataId() {
        return authDataId;
    }

    /**
     * 设置 数据权限表id : 关联数据权限表id 字段:sfxie_sys_auth_role_menu.auth_data_id
     *
     * @param authDataId sfxie_sys_auth_role_menu.auth_data_id, 数据权限表id : 关联数据权限表id
     */
    public void setAuthDataId(String authDataId) {
        this.authDataId = authDataId == null ? null : authDataId.trim();
    }

    /**
     * 获取 上一级公司 : 上上一级公司，也就是这一级的上一级公司 字段:sfxie_sys_auth_role_menu.owner_company_code
     *
     * @return sfxie_sys_auth_role_menu.owner_company_code, 上一级公司 : 上上一级公司，也就是这一级的上一级公司
     */
    public String getOwnerCompanyCode() {
        return ownerCompanyCode;
    }

    /**
     * 设置 上一级公司 : 上上一级公司，也就是这一级的上一级公司 字段:sfxie_sys_auth_role_menu.owner_company_code
     *
     * @param ownerCompanyCode sfxie_sys_auth_role_menu.owner_company_code, 上一级公司 : 上上一级公司，也就是这一级的上一级公司
     */
    public void setOwnerCompanyCode(String ownerCompanyCode) {
        this.ownerCompanyCode = ownerCompanyCode == null ? null : ownerCompanyCode.trim();
    }

    /**
     * 获取 公司角色关联表id : 公司角色关联表id 字段:sfxie_sys_auth_role_menu.company_role_id
     *
     * @return sfxie_sys_auth_role_menu.company_role_id, 公司角色关联表id : 公司角色关联表id
     */
    public String getCompanyRoleId() {
        return companyRoleId;
    }

    /**
     * 设置 公司角色关联表id : 公司角色关联表id 字段:sfxie_sys_auth_role_menu.company_role_id
     *
     * @param companyRoleId sfxie_sys_auth_role_menu.company_role_id, 公司角色关联表id : 公司角色关联表id
     */
    public void setCompanyRoleId(String companyRoleId) {
        this.companyRoleId = companyRoleId == null ? null : companyRoleId.trim();
    }

    /**
     * 获取 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_auth_role_menu.partition_company
     *
     * @return sfxie_sys_auth_role_menu.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public String getPartitionCompany() {
        return partitionCompany;
    }

    /**
     * 设置 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_auth_role_menu.partition_company
     *
     * @param partitionCompany sfxie_sys_auth_role_menu.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public void setPartitionCompany(String partitionCompany) {
        this.partitionCompany = partitionCompany == null ? null : partitionCompany.trim();
    }
}