package com.sfxie.services.center.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sfxie_sys_auth_data
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class SfxieSysAuthData {
    /**
     *  记录主键 : 记录主键,所属表字段为sfxie_sys_auth_data.id_
     */
    private String id;

    /**
     *  角色主键 : 角色代码,所属表字段为sfxie_sys_auth_data.role_id
     */
    private String roleId;

    /**
     *  资源名称 : 资源名称,所属表字段为sfxie_sys_auth_data.resource_name
     */
    private String resourceName;

    /**
     *  资源代码 : 资源代码,所属表字段为sfxie_sys_auth_data.resource_code
     */
    private String resourceCode;

    /**
     *  排序字段 : 排序字段,所属表字段为sfxie_sys_auth_data.sequence_no
     */
    private Integer sequenceNo;

    /**
     *  创建时间 : 创建时间,所属表字段为sfxie_sys_auth_data.create_time
     */
    private Date createTime;

    /**
     *  记录创建人 : 记录创建人,所属表字段为sfxie_sys_auth_data.create_user
     */
    private String createUser;

    /**
     *  最后修改时间 : 最后修改时间,所属表字段为sfxie_sys_auth_data.update_time
     */
    private Date updateTime;

    /**
     *  最后修改人 : 最后修改人,所属表字段为sfxie_sys_auth_data.update_user
     */
    private String updateUser;

    /**
     *  是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效,所属表字段为sfxie_sys_auth_data.is_valid
     */
    private String isValid;

    /**
     *  上一级公司 : 上上一级公司，也就是这一级的上一级公司,所属表字段为sfxie_sys_auth_data.owner_company_code
     */
    private String ownerCompanyCode;

    /**
     *  数据权限sql查询语句,所属表字段为sfxie_sys_auth_data.sql_
     */
    private String sql;

    /**
     *  角色菜单关联表id : 关联角色菜单关联表id,所属表字段为sfxie_sys_auth_data.role_menu_id
     */
    private String roleMenuId;

    /**
     *  java处理类 : 用java处理类获取sql或者用户列表,所属表字段为sfxie_sys_auth_data.dealer_class
     */
    private String dealerClass;

    /**
     *  创建公司 : 创建公司,所属表字段为sfxie_sys_auth_data.create_company_id
     */
    private String createCompanyId;

    /**
     *  分区字段 : 分区字段,从用户公司代码字段取值,所属表字段为sfxie_sys_auth_data.partition_company
     */
    private String partitionCompany;

    /**
     * 获取 记录主键 : 记录主键 字段:sfxie_sys_auth_data.id_
     *
     * @return sfxie_sys_auth_data.id_, 记录主键 : 记录主键
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 记录主键 : 记录主键 字段:sfxie_sys_auth_data.id_
     *
     * @param id sfxie_sys_auth_data.id_, 记录主键 : 记录主键
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 角色主键 : 角色代码 字段:sfxie_sys_auth_data.role_id
     *
     * @return sfxie_sys_auth_data.role_id, 角色主键 : 角色代码
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * 设置 角色主键 : 角色代码 字段:sfxie_sys_auth_data.role_id
     *
     * @param roleId sfxie_sys_auth_data.role_id, 角色主键 : 角色代码
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * 获取 资源名称 : 资源名称 字段:sfxie_sys_auth_data.resource_name
     *
     * @return sfxie_sys_auth_data.resource_name, 资源名称 : 资源名称
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * 设置 资源名称 : 资源名称 字段:sfxie_sys_auth_data.resource_name
     *
     * @param resourceName sfxie_sys_auth_data.resource_name, 资源名称 : 资源名称
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * 获取 资源代码 : 资源代码 字段:sfxie_sys_auth_data.resource_code
     *
     * @return sfxie_sys_auth_data.resource_code, 资源代码 : 资源代码
     */
    public String getResourceCode() {
        return resourceCode;
    }

    /**
     * 设置 资源代码 : 资源代码 字段:sfxie_sys_auth_data.resource_code
     *
     * @param resourceCode sfxie_sys_auth_data.resource_code, 资源代码 : 资源代码
     */
    public void setResourceCode(String resourceCode) {
        this.resourceCode = resourceCode == null ? null : resourceCode.trim();
    }

    /**
     * 获取 排序字段 : 排序字段 字段:sfxie_sys_auth_data.sequence_no
     *
     * @return sfxie_sys_auth_data.sequence_no, 排序字段 : 排序字段
     */
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    /**
     * 设置 排序字段 : 排序字段 字段:sfxie_sys_auth_data.sequence_no
     *
     * @param sequenceNo sfxie_sys_auth_data.sequence_no, 排序字段 : 排序字段
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * 获取 创建时间 : 创建时间 字段:sfxie_sys_auth_data.create_time
     *
     * @return sfxie_sys_auth_data.create_time, 创建时间 : 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 : 创建时间 字段:sfxie_sys_auth_data.create_time
     *
     * @param createTime sfxie_sys_auth_data.create_time, 创建时间 : 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 记录创建人 : 记录创建人 字段:sfxie_sys_auth_data.create_user
     *
     * @return sfxie_sys_auth_data.create_user, 记录创建人 : 记录创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * 设置 记录创建人 : 记录创建人 字段:sfxie_sys_auth_data.create_user
     *
     * @param createUser sfxie_sys_auth_data.create_user, 记录创建人 : 记录创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * 获取 最后修改时间 : 最后修改时间 字段:sfxie_sys_auth_data.update_time
     *
     * @return sfxie_sys_auth_data.update_time, 最后修改时间 : 最后修改时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置 最后修改时间 : 最后修改时间 字段:sfxie_sys_auth_data.update_time
     *
     * @param updateTime sfxie_sys_auth_data.update_time, 最后修改时间 : 最后修改时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取 最后修改人 : 最后修改人 字段:sfxie_sys_auth_data.update_user
     *
     * @return sfxie_sys_auth_data.update_user, 最后修改人 : 最后修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * 设置 最后修改人 : 最后修改人 字段:sfxie_sys_auth_data.update_user
     *
     * @param updateUser sfxie_sys_auth_data.update_user, 最后修改人 : 最后修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * 获取 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_auth_data.is_valid
     *
     * @return sfxie_sys_auth_data.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * 设置 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_auth_data.is_valid
     *
     * @param isValid sfxie_sys_auth_data.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * 获取 上一级公司 : 上上一级公司，也就是这一级的上一级公司 字段:sfxie_sys_auth_data.owner_company_code
     *
     * @return sfxie_sys_auth_data.owner_company_code, 上一级公司 : 上上一级公司，也就是这一级的上一级公司
     */
    public String getOwnerCompanyCode() {
        return ownerCompanyCode;
    }

    /**
     * 设置 上一级公司 : 上上一级公司，也就是这一级的上一级公司 字段:sfxie_sys_auth_data.owner_company_code
     *
     * @param ownerCompanyCode sfxie_sys_auth_data.owner_company_code, 上一级公司 : 上上一级公司，也就是这一级的上一级公司
     */
    public void setOwnerCompanyCode(String ownerCompanyCode) {
        this.ownerCompanyCode = ownerCompanyCode == null ? null : ownerCompanyCode.trim();
    }

    /**
     * 获取 数据权限sql查询语句 字段:sfxie_sys_auth_data.sql_
     *
     * @return sfxie_sys_auth_data.sql_, 数据权限sql查询语句
     */
    public String getSql() {
        return sql;
    }

    /**
     * 设置 数据权限sql查询语句 字段:sfxie_sys_auth_data.sql_
     *
     * @param sql sfxie_sys_auth_data.sql_, 数据权限sql查询语句
     */
    public void setSql(String sql) {
        this.sql = sql == null ? null : sql.trim();
    }

    /**
     * 获取 角色菜单关联表id : 关联角色菜单关联表id 字段:sfxie_sys_auth_data.role_menu_id
     *
     * @return sfxie_sys_auth_data.role_menu_id, 角色菜单关联表id : 关联角色菜单关联表id
     */
    public String getRoleMenuId() {
        return roleMenuId;
    }

    /**
     * 设置 角色菜单关联表id : 关联角色菜单关联表id 字段:sfxie_sys_auth_data.role_menu_id
     *
     * @param roleMenuId sfxie_sys_auth_data.role_menu_id, 角色菜单关联表id : 关联角色菜单关联表id
     */
    public void setRoleMenuId(String roleMenuId) {
        this.roleMenuId = roleMenuId == null ? null : roleMenuId.trim();
    }

    /**
     * 获取 java处理类 : 用java处理类获取sql或者用户列表 字段:sfxie_sys_auth_data.dealer_class
     *
     * @return sfxie_sys_auth_data.dealer_class, java处理类 : 用java处理类获取sql或者用户列表
     */
    public String getDealerClass() {
        return dealerClass;
    }

    /**
     * 设置 java处理类 : 用java处理类获取sql或者用户列表 字段:sfxie_sys_auth_data.dealer_class
     *
     * @param dealerClass sfxie_sys_auth_data.dealer_class, java处理类 : 用java处理类获取sql或者用户列表
     */
    public void setDealerClass(String dealerClass) {
        this.dealerClass = dealerClass == null ? null : dealerClass.trim();
    }

    /**
     * 获取 创建公司 : 创建公司 字段:sfxie_sys_auth_data.create_company_id
     *
     * @return sfxie_sys_auth_data.create_company_id, 创建公司 : 创建公司
     */
    public String getCreateCompanyId() {
        return createCompanyId;
    }

    /**
     * 设置 创建公司 : 创建公司 字段:sfxie_sys_auth_data.create_company_id
     *
     * @param createCompanyId sfxie_sys_auth_data.create_company_id, 创建公司 : 创建公司
     */
    public void setCreateCompanyId(String createCompanyId) {
        this.createCompanyId = createCompanyId == null ? null : createCompanyId.trim();
    }

    /**
     * 获取 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_auth_data.partition_company
     *
     * @return sfxie_sys_auth_data.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public String getPartitionCompany() {
        return partitionCompany;
    }

    /**
     * 设置 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_auth_data.partition_company
     *
     * @param partitionCompany sfxie_sys_auth_data.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public void setPartitionCompany(String partitionCompany) {
        this.partitionCompany = partitionCompany == null ? null : partitionCompany.trim();
    }
}