package com.sfxie.services.center.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sfxie_sys_post
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class SfxieSysPost {
    /**
     *  记录主键 : 记录主键,所属表字段为sfxie_sys_post.id_
     */
    private String id;

    /**
     *  岗位代码 : 岗位代码,所属表字段为sfxie_sys_post.post_code
     */
    private String postCode;

    /**
     *  部门主键 : 部门主键,所属表字段为sfxie_sys_post.department_id
     */
    private String departmentId;

    /**
     *  岗位名称 : 岗位名称,所属表字段为sfxie_sys_post.post_name
     */
    private String postName;

    /**
     *  排序字段 : 排序字段,所属表字段为sfxie_sys_post.sequence_no
     */
    private Integer sequenceNo;

    /**
     *  岗位级别 : 0表示第一岗位,1表示第2岗位,2表示第3岗位,所属表字段为sfxie_sys_post.post_level
     */
    private String postLevel;

    /**
     *  创建时间 : 创建时间,所属表字段为sfxie_sys_post.create_time
     */
    private Date createTime;

    /**
     *  记录创建人 : 记录创建人,所属表字段为sfxie_sys_post.create_user
     */
    private String createUser;

    /**
     *  最后修改时间 : 最后修改时间,所属表字段为sfxie_sys_post.update_time
     */
    private Date updateTime;

    /**
     *  最后修改人 : 最后修改人,所属表字段为sfxie_sys_post.update_user
     */
    private String updateUser;

    /**
     *  公司主键 : 公司主键,所属表字段为sfxie_sys_post.company_id
     */
    private String companyId;

    /**
     *  父主键 : 关联父主键,所属表字段为sfxie_sys_post.parent_id
     */
    private String parentId;

    /**
     *  是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效,所属表字段为sfxie_sys_post.is_valid
     */
    private String isValid;

    /**
     *  创建公司 : 创建公司,所属表字段为sfxie_sys_post.create_company_id
     */
    private String createCompanyId;

    /**
     *  分区字段 : 分区字段,从用户公司代码字段取值,所属表字段为sfxie_sys_post.partition_company
     */
    private String partitionCompany;

    /**
     * 获取 记录主键 : 记录主键 字段:sfxie_sys_post.id_
     *
     * @return sfxie_sys_post.id_, 记录主键 : 记录主键
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 记录主键 : 记录主键 字段:sfxie_sys_post.id_
     *
     * @param id sfxie_sys_post.id_, 记录主键 : 记录主键
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 岗位代码 : 岗位代码 字段:sfxie_sys_post.post_code
     *
     * @return sfxie_sys_post.post_code, 岗位代码 : 岗位代码
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * 设置 岗位代码 : 岗位代码 字段:sfxie_sys_post.post_code
     *
     * @param postCode sfxie_sys_post.post_code, 岗位代码 : 岗位代码
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * 获取 部门主键 : 部门主键 字段:sfxie_sys_post.department_id
     *
     * @return sfxie_sys_post.department_id, 部门主键 : 部门主键
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * 设置 部门主键 : 部门主键 字段:sfxie_sys_post.department_id
     *
     * @param departmentId sfxie_sys_post.department_id, 部门主键 : 部门主键
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * 获取 岗位名称 : 岗位名称 字段:sfxie_sys_post.post_name
     *
     * @return sfxie_sys_post.post_name, 岗位名称 : 岗位名称
     */
    public String getPostName() {
        return postName;
    }

    /**
     * 设置 岗位名称 : 岗位名称 字段:sfxie_sys_post.post_name
     *
     * @param postName sfxie_sys_post.post_name, 岗位名称 : 岗位名称
     */
    public void setPostName(String postName) {
        this.postName = postName == null ? null : postName.trim();
    }

    /**
     * 获取 排序字段 : 排序字段 字段:sfxie_sys_post.sequence_no
     *
     * @return sfxie_sys_post.sequence_no, 排序字段 : 排序字段
     */
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    /**
     * 设置 排序字段 : 排序字段 字段:sfxie_sys_post.sequence_no
     *
     * @param sequenceNo sfxie_sys_post.sequence_no, 排序字段 : 排序字段
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * 获取 岗位级别 : 0表示第一岗位,1表示第2岗位,2表示第3岗位 字段:sfxie_sys_post.post_level
     *
     * @return sfxie_sys_post.post_level, 岗位级别 : 0表示第一岗位,1表示第2岗位,2表示第3岗位
     */
    public String getPostLevel() {
        return postLevel;
    }

    /**
     * 设置 岗位级别 : 0表示第一岗位,1表示第2岗位,2表示第3岗位 字段:sfxie_sys_post.post_level
     *
     * @param postLevel sfxie_sys_post.post_level, 岗位级别 : 0表示第一岗位,1表示第2岗位,2表示第3岗位
     */
    public void setPostLevel(String postLevel) {
        this.postLevel = postLevel == null ? null : postLevel.trim();
    }

    /**
     * 获取 创建时间 : 创建时间 字段:sfxie_sys_post.create_time
     *
     * @return sfxie_sys_post.create_time, 创建时间 : 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 : 创建时间 字段:sfxie_sys_post.create_time
     *
     * @param createTime sfxie_sys_post.create_time, 创建时间 : 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 记录创建人 : 记录创建人 字段:sfxie_sys_post.create_user
     *
     * @return sfxie_sys_post.create_user, 记录创建人 : 记录创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * 设置 记录创建人 : 记录创建人 字段:sfxie_sys_post.create_user
     *
     * @param createUser sfxie_sys_post.create_user, 记录创建人 : 记录创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * 获取 最后修改时间 : 最后修改时间 字段:sfxie_sys_post.update_time
     *
     * @return sfxie_sys_post.update_time, 最后修改时间 : 最后修改时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置 最后修改时间 : 最后修改时间 字段:sfxie_sys_post.update_time
     *
     * @param updateTime sfxie_sys_post.update_time, 最后修改时间 : 最后修改时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取 最后修改人 : 最后修改人 字段:sfxie_sys_post.update_user
     *
     * @return sfxie_sys_post.update_user, 最后修改人 : 最后修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * 设置 最后修改人 : 最后修改人 字段:sfxie_sys_post.update_user
     *
     * @param updateUser sfxie_sys_post.update_user, 最后修改人 : 最后修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * 获取 公司主键 : 公司主键 字段:sfxie_sys_post.company_id
     *
     * @return sfxie_sys_post.company_id, 公司主键 : 公司主键
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * 设置 公司主键 : 公司主键 字段:sfxie_sys_post.company_id
     *
     * @param companyId sfxie_sys_post.company_id, 公司主键 : 公司主键
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * 获取 父主键 : 关联父主键 字段:sfxie_sys_post.parent_id
     *
     * @return sfxie_sys_post.parent_id, 父主键 : 关联父主键
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * 设置 父主键 : 关联父主键 字段:sfxie_sys_post.parent_id
     *
     * @param parentId sfxie_sys_post.parent_id, 父主键 : 关联父主键
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * 获取 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_post.is_valid
     *
     * @return sfxie_sys_post.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * 设置 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_post.is_valid
     *
     * @param isValid sfxie_sys_post.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * 获取 创建公司 : 创建公司 字段:sfxie_sys_post.create_company_id
     *
     * @return sfxie_sys_post.create_company_id, 创建公司 : 创建公司
     */
    public String getCreateCompanyId() {
        return createCompanyId;
    }

    /**
     * 设置 创建公司 : 创建公司 字段:sfxie_sys_post.create_company_id
     *
     * @param createCompanyId sfxie_sys_post.create_company_id, 创建公司 : 创建公司
     */
    public void setCreateCompanyId(String createCompanyId) {
        this.createCompanyId = createCompanyId == null ? null : createCompanyId.trim();
    }

    /**
     * 获取 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_post.partition_company
     *
     * @return sfxie_sys_post.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public String getPartitionCompany() {
        return partitionCompany;
    }

    /**
     * 设置 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_post.partition_company
     *
     * @param partitionCompany sfxie_sys_post.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public void setPartitionCompany(String partitionCompany) {
        this.partitionCompany = partitionCompany == null ? null : partitionCompany.trim();
    }
}