package com.sfxie.services.center.pojo;

import java.util.Date;

import com.sfxie.component.node.CustomerNodeEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sfxie_sys_menu
 *
 * @mbg.generated do_not_delete_during_merge Mon May 01 19:06:36 CST 2017
 */
public class SfxieSysMenu extends CustomerNodeEntity{
    /**
     *  记录主键 : 记录主键,所属表字段为sfxie_sys_menu.id_
     */
    private String id;

    /**
     *  菜单代码 : 菜单代码,所属表字段为sfxie_sys_menu.menu_code
     */
    private String menuCode;

    /**
     *  关联system_id : 关联web_system表,所属表字段为sfxie_sys_menu.system_id
     */
    private String systemId;

    /**
     *  数据权限id : 关联数据权限主键,所属表字段为sfxie_sys_menu.auth_data_id
     */
    private String authDataId;

    /**
     *  菜单名称 : 菜单名称,所属表字段为sfxie_sys_menu.menu_name
     */
    private String menuName;

    /**
     *  资源 : 资源,所属表字段为sfxie_sys_menu.url
     */
    private String url;

    /**
     *  描述 : 描述,所属表字段为sfxie_sys_menu.description
     */
    private String description;

    /**
     *  繁体菜单名称 : 繁体菜单名称,所属表字段为sfxie_sys_menu.menu_name_tw
     */
    private String menuNameTw;

    /**
     *  网站标识 : 网站标识 smis ems sms,所属表字段为sfxie_sys_menu.webside
     */
    private String webside;

    /**
     *  排序字段 : 排序字段,所属表字段为sfxie_sys_menu.sequence_no
     */
    private Integer sequenceNo;

    /**
     *  父主键 : 关联父主键,所属表字段为sfxie_sys_menu.parent_id
     */
    private String parentId;

    /**
     *  最后修改时间 : 最后修改时间,所属表字段为sfxie_sys_menu.update_time
     */
    private Date updateTime;

    /**
     *  最后修改人 : 最后修改人,所属表字段为sfxie_sys_menu.update_user
     */
    private String updateUser;

    /**
     *  创建时间 : 创建时间,所属表字段为sfxie_sys_menu.create_time
     */
    private Date createTime;

    /**
     *  记录创建人 : 记录创建人,所属表字段为sfxie_sys_menu.create_user
     */
    private String createUser;

    /**
     *  是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效,所属表字段为sfxie_sys_menu.is_valid
     */
    private String isValid;

    /**
     *  all_parent_id,所属表字段为sfxie_sys_menu.all_parent_id
     */
    private String allParentId;

    /**
     *  分区字段 : 分区字段,从用户公司代码字段取值,所属表字段为sfxie_sys_menu.partition_company
     */
    private String partitionCompany;

    /**
     * 获取 记录主键 : 记录主键 字段:sfxie_sys_menu.id_
     *
     * @return sfxie_sys_menu.id_, 记录主键 : 记录主键
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 记录主键 : 记录主键 字段:sfxie_sys_menu.id_
     *
     * @param id sfxie_sys_menu.id_, 记录主键 : 记录主键
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 菜单代码 : 菜单代码 字段:sfxie_sys_menu.menu_code
     *
     * @return sfxie_sys_menu.menu_code, 菜单代码 : 菜单代码
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * 设置 菜单代码 : 菜单代码 字段:sfxie_sys_menu.menu_code
     *
     * @param menuCode sfxie_sys_menu.menu_code, 菜单代码 : 菜单代码
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }

    /**
     * 获取 关联system_id : 关联web_system表 字段:sfxie_sys_menu.system_id
     *
     * @return sfxie_sys_menu.system_id, 关联system_id : 关联web_system表
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * 设置 关联system_id : 关联web_system表 字段:sfxie_sys_menu.system_id
     *
     * @param systemId sfxie_sys_menu.system_id, 关联system_id : 关联web_system表
     */
    public void setSystemId(String systemId) {
        this.systemId = systemId == null ? null : systemId.trim();
    }

    /**
     * 获取 数据权限id : 关联数据权限主键 字段:sfxie_sys_menu.auth_data_id
     *
     * @return sfxie_sys_menu.auth_data_id, 数据权限id : 关联数据权限主键
     */
    public String getAuthDataId() {
        return authDataId;
    }

    /**
     * 设置 数据权限id : 关联数据权限主键 字段:sfxie_sys_menu.auth_data_id
     *
     * @param authDataId sfxie_sys_menu.auth_data_id, 数据权限id : 关联数据权限主键
     */
    public void setAuthDataId(String authDataId) {
        this.authDataId = authDataId == null ? null : authDataId.trim();
    }

    /**
     * 获取 菜单名称 : 菜单名称 字段:sfxie_sys_menu.menu_name
     *
     * @return sfxie_sys_menu.menu_name, 菜单名称 : 菜单名称
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * 设置 菜单名称 : 菜单名称 字段:sfxie_sys_menu.menu_name
     *
     * @param menuName sfxie_sys_menu.menu_name, 菜单名称 : 菜单名称
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * 获取 资源 : 资源 字段:sfxie_sys_menu.url
     *
     * @return sfxie_sys_menu.url, 资源 : 资源
     */
    public String getUrl() {
        return url;
    }

    /**
     * 设置 资源 : 资源 字段:sfxie_sys_menu.url
     *
     * @param url sfxie_sys_menu.url, 资源 : 资源
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * 获取 描述 : 描述 字段:sfxie_sys_menu.description
     *
     * @return sfxie_sys_menu.description, 描述 : 描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置 描述 : 描述 字段:sfxie_sys_menu.description
     *
     * @param description sfxie_sys_menu.description, 描述 : 描述
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 获取 繁体菜单名称 : 繁体菜单名称 字段:sfxie_sys_menu.menu_name_tw
     *
     * @return sfxie_sys_menu.menu_name_tw, 繁体菜单名称 : 繁体菜单名称
     */
    public String getMenuNameTw() {
        return menuNameTw;
    }

    /**
     * 设置 繁体菜单名称 : 繁体菜单名称 字段:sfxie_sys_menu.menu_name_tw
     *
     * @param menuNameTw sfxie_sys_menu.menu_name_tw, 繁体菜单名称 : 繁体菜单名称
     */
    public void setMenuNameTw(String menuNameTw) {
        this.menuNameTw = menuNameTw == null ? null : menuNameTw.trim();
    }

    /**
     * 获取 网站标识 : 网站标识 smis ems sms 字段:sfxie_sys_menu.webside
     *
     * @return sfxie_sys_menu.webside, 网站标识 : 网站标识 smis ems sms
     */
    public String getWebside() {
        return webside;
    }

    /**
     * 设置 网站标识 : 网站标识 smis ems sms 字段:sfxie_sys_menu.webside
     *
     * @param webside sfxie_sys_menu.webside, 网站标识 : 网站标识 smis ems sms
     */
    public void setWebside(String webside) {
        this.webside = webside == null ? null : webside.trim();
    }

    /**
     * 获取 排序字段 : 排序字段 字段:sfxie_sys_menu.sequence_no
     *
     * @return sfxie_sys_menu.sequence_no, 排序字段 : 排序字段
     */
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    /**
     * 设置 排序字段 : 排序字段 字段:sfxie_sys_menu.sequence_no
     *
     * @param sequenceNo sfxie_sys_menu.sequence_no, 排序字段 : 排序字段
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * 获取 父主键 : 关联父主键 字段:sfxie_sys_menu.parent_id
     *
     * @return sfxie_sys_menu.parent_id, 父主键 : 关联父主键
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * 设置 父主键 : 关联父主键 字段:sfxie_sys_menu.parent_id
     *
     * @param parentId sfxie_sys_menu.parent_id, 父主键 : 关联父主键
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * 获取 最后修改时间 : 最后修改时间 字段:sfxie_sys_menu.update_time
     *
     * @return sfxie_sys_menu.update_time, 最后修改时间 : 最后修改时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置 最后修改时间 : 最后修改时间 字段:sfxie_sys_menu.update_time
     *
     * @param updateTime sfxie_sys_menu.update_time, 最后修改时间 : 最后修改时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取 最后修改人 : 最后修改人 字段:sfxie_sys_menu.update_user
     *
     * @return sfxie_sys_menu.update_user, 最后修改人 : 最后修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * 设置 最后修改人 : 最后修改人 字段:sfxie_sys_menu.update_user
     *
     * @param updateUser sfxie_sys_menu.update_user, 最后修改人 : 最后修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * 获取 创建时间 : 创建时间 字段:sfxie_sys_menu.create_time
     *
     * @return sfxie_sys_menu.create_time, 创建时间 : 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 : 创建时间 字段:sfxie_sys_menu.create_time
     *
     * @param createTime sfxie_sys_menu.create_time, 创建时间 : 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 记录创建人 : 记录创建人 字段:sfxie_sys_menu.create_user
     *
     * @return sfxie_sys_menu.create_user, 记录创建人 : 记录创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * 设置 记录创建人 : 记录创建人 字段:sfxie_sys_menu.create_user
     *
     * @param createUser sfxie_sys_menu.create_user, 记录创建人 : 记录创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * 获取 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_menu.is_valid
     *
     * @return sfxie_sys_menu.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * 设置 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_menu.is_valid
     *
     * @param isValid sfxie_sys_menu.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * 获取 all_parent_id 字段:sfxie_sys_menu.all_parent_id
     *
     * @return sfxie_sys_menu.all_parent_id, all_parent_id
     */
    public String getAllParentId() {
        return allParentId;
    }

    /**
     * 设置 all_parent_id 字段:sfxie_sys_menu.all_parent_id
     *
     * @param allParentId sfxie_sys_menu.all_parent_id, all_parent_id
     */
    public void setAllParentId(String allParentId) {
        this.allParentId = allParentId == null ? null : allParentId.trim();
    }

    /**
     * 获取 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_menu.partition_company
     *
     * @return sfxie_sys_menu.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public String getPartitionCompany() {
        return partitionCompany;
    }

    /**
     * 设置 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_menu.partition_company
     *
     * @param partitionCompany sfxie_sys_menu.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public void setPartitionCompany(String partitionCompany) {
        this.partitionCompany = partitionCompany == null ? null : partitionCompany.trim();
    }
}