package com.sfxie.services.center.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sfxie_sys_role
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 08 08:42:00 CST 2017
 */
public class SfxieSysRole {
    /**
     *  记录主键 : 记录主键,所属表字段为sfxie_sys_role.id_
     */
    private String id;

    /**
     *  角色代码 : 角色代码,所属表字段为sfxie_sys_role.role_code
     */
    private String roleCode;

    /**
     *  角色名称 : 角色名称,所属表字段为sfxie_sys_role.role_name
     */
    private String roleName;

    /**
     *  描述 : 描述,所属表字段为sfxie_sys_role.description
     */
    private String description;

    /**
     *  角色英文名称 : 角色英文名称,所属表字段为sfxie_sys_role.role_name_en
     */
    private String roleNameEn;

    /**
     *  最后修改时间 : 最后修改时间,所属表字段为sfxie_sys_role.update_time
     */
    private Date updateTime;

    /**
     *  最后修改人 : 最后修改人,所属表字段为sfxie_sys_role.update_user
     */
    private String updateUser;

    /**
     *  创建时间 : 创建时间,所属表字段为sfxie_sys_role.create_time
     */
    private Date createTime;

    /**
     *  记录创建人 : 记录创建人,所属表字段为sfxie_sys_role.create_user
     */
    private String createUser;

    /**
     *  排序字段 : 排序字段,所属表字段为sfxie_sys_role.sequence_no
     */
    private Integer sequenceNo;

    /**
     *  是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效,所属表字段为sfxie_sys_role.is_valid
     */
    private String isValid;

    /**
     *  创建公司 : 创建公司,所属表字段为sfxie_sys_role.create_company_id
     */
    private String createCompanyId;

    /**
     *  分区字段 : 分区字段,从用户公司代码字段取值,所属表字段为sfxie_sys_role.partition_company
     */
    private String partitionCompany;

    /**
     * 获取 记录主键 : 记录主键 字段:sfxie_sys_role.id_
     *
     * @return sfxie_sys_role.id_, 记录主键 : 记录主键
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 记录主键 : 记录主键 字段:sfxie_sys_role.id_
     *
     * @param id sfxie_sys_role.id_, 记录主键 : 记录主键
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 角色代码 : 角色代码 字段:sfxie_sys_role.role_code
     *
     * @return sfxie_sys_role.role_code, 角色代码 : 角色代码
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * 设置 角色代码 : 角色代码 字段:sfxie_sys_role.role_code
     *
     * @param roleCode sfxie_sys_role.role_code, 角色代码 : 角色代码
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * 获取 角色名称 : 角色名称 字段:sfxie_sys_role.role_name
     *
     * @return sfxie_sys_role.role_name, 角色名称 : 角色名称
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * 设置 角色名称 : 角色名称 字段:sfxie_sys_role.role_name
     *
     * @param roleName sfxie_sys_role.role_name, 角色名称 : 角色名称
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * 获取 描述 : 描述 字段:sfxie_sys_role.description
     *
     * @return sfxie_sys_role.description, 描述 : 描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置 描述 : 描述 字段:sfxie_sys_role.description
     *
     * @param description sfxie_sys_role.description, 描述 : 描述
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 获取 角色英文名称 : 角色英文名称 字段:sfxie_sys_role.role_name_en
     *
     * @return sfxie_sys_role.role_name_en, 角色英文名称 : 角色英文名称
     */
    public String getRoleNameEn() {
        return roleNameEn;
    }

    /**
     * 设置 角色英文名称 : 角色英文名称 字段:sfxie_sys_role.role_name_en
     *
     * @param roleNameEn sfxie_sys_role.role_name_en, 角色英文名称 : 角色英文名称
     */
    public void setRoleNameEn(String roleNameEn) {
        this.roleNameEn = roleNameEn == null ? null : roleNameEn.trim();
    }

    /**
     * 获取 最后修改时间 : 最后修改时间 字段:sfxie_sys_role.update_time
     *
     * @return sfxie_sys_role.update_time, 最后修改时间 : 最后修改时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置 最后修改时间 : 最后修改时间 字段:sfxie_sys_role.update_time
     *
     * @param updateTime sfxie_sys_role.update_time, 最后修改时间 : 最后修改时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取 最后修改人 : 最后修改人 字段:sfxie_sys_role.update_user
     *
     * @return sfxie_sys_role.update_user, 最后修改人 : 最后修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * 设置 最后修改人 : 最后修改人 字段:sfxie_sys_role.update_user
     *
     * @param updateUser sfxie_sys_role.update_user, 最后修改人 : 最后修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * 获取 创建时间 : 创建时间 字段:sfxie_sys_role.create_time
     *
     * @return sfxie_sys_role.create_time, 创建时间 : 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 : 创建时间 字段:sfxie_sys_role.create_time
     *
     * @param createTime sfxie_sys_role.create_time, 创建时间 : 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 记录创建人 : 记录创建人 字段:sfxie_sys_role.create_user
     *
     * @return sfxie_sys_role.create_user, 记录创建人 : 记录创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * 设置 记录创建人 : 记录创建人 字段:sfxie_sys_role.create_user
     *
     * @param createUser sfxie_sys_role.create_user, 记录创建人 : 记录创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * 获取 排序字段 : 排序字段 字段:sfxie_sys_role.sequence_no
     *
     * @return sfxie_sys_role.sequence_no, 排序字段 : 排序字段
     */
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    /**
     * 设置 排序字段 : 排序字段 字段:sfxie_sys_role.sequence_no
     *
     * @param sequenceNo sfxie_sys_role.sequence_no, 排序字段 : 排序字段
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * 获取 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_role.is_valid
     *
     * @return sfxie_sys_role.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * 设置 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效 字段:sfxie_sys_role.is_valid
     *
     * @param isValid sfxie_sys_role.is_valid, 是否有效 : 是否有效,Y:是;N:否
控制是否在公司任职有效
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * 获取 创建公司 : 创建公司 字段:sfxie_sys_role.create_company_id
     *
     * @return sfxie_sys_role.create_company_id, 创建公司 : 创建公司
     */
    public String getCreateCompanyId() {
        return createCompanyId;
    }

    /**
     * 设置 创建公司 : 创建公司 字段:sfxie_sys_role.create_company_id
     *
     * @param createCompanyId sfxie_sys_role.create_company_id, 创建公司 : 创建公司
     */
    public void setCreateCompanyId(String createCompanyId) {
        this.createCompanyId = createCompanyId == null ? null : createCompanyId.trim();
    }

    /**
     * 获取 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_role.partition_company
     *
     * @return sfxie_sys_role.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public String getPartitionCompany() {
        return partitionCompany;
    }

    /**
     * 设置 分区字段 : 分区字段,从用户公司代码字段取值 字段:sfxie_sys_role.partition_company
     *
     * @param partitionCompany sfxie_sys_role.partition_company, 分区字段 : 分区字段,从用户公司代码字段取值
     */
    public void setPartitionCompany(String partitionCompany) {
        this.partitionCompany = partitionCompany == null ? null : partitionCompany.trim();
    }
}